### PR TITLE
kitty

### PR DESCRIPTION
**Pull request by Dread0-0**
kitty 👍

### CODE REVIEW

**Comment by jaytsdev** [comment]
among us

**Comment by Dread0-0** [comment]
> among us

sussy bals

**Comment by jaytsdev** [comment]
> > among us
> 
> sussy bals

i COULD merge this or i could go to sleep.. :trollface:

**Comment by Dread0-0** [comment]
> > > among us
> > 
> > sussy bals
> 
> i COULD merge this or i could go to sleep.. :trollface:

165.23.170.13

**Comment by jaytsdev** [comment]
> > > > among us
> > > 
> > > sussy bals
> > 
> > i COULD merge this or i could go to sleep.. :trollface:
> 
> 165.23.170.13

😨

**Comment by jaytsdev** [comment]
update help.js too because i am NOT!!! doing that im lazy rn

**Comment by Dread0-0** [comment]
> update help.js too because i am NOT!!! doing that im lazy rn

too busy playing Factorio, if I remember I'll do it later

**Comment by jaytsdev** [comment]
> > update help.js too because i am NOT!!! doing that im lazy rn
> 
> too busy playing Factorio, if I remember I'll do it later 

do it now or im pulling your ip and coming to your habitat of living

**Comment by Dread0-0** [comment]
> > > update help.js too because i am NOT!!! doing that im lazy rn
> > 
> > too busy playing Factorio, if I remember I'll do it later 
> 
> do it now or im pulling your ip and coming to your habitat of living

my parents aren't home 😍

**Comment by jaytsdev** [comment]
> > > > update help.js too because i am NOT!!! doing that im lazy rn
> > > 
> > > too busy playing Factorio, if I remember I'll do it later 
> > 
> > do it now or im pulling your ip and coming to your habitat of living
> 
> my parents aren't home 😍

yk what forget i said anything 💀

**Pull request merged**
