### PR TITLE
Update profile.js

### PR DESCRIPTION
**Pull request by Prim-Dev**
Changed Error.Emoji to Success_Emoji for deletion command cos jay is lazy

### CODE REVIEW

**Comment by jormy** [comment]
smh jay

**Comment by jaytsdev** [comment]
> smh jay

shush before i do bad things

# very bad things

**Comment by Prim-Dev** [comment]
> 

i love men

# LOVE THEM

**Comment by jormy** [comment]
> 

what kind of bad things 😳

**Comment by jormy** [comment]
> > smh jay
> 
> shush before i do bad things
> 
> # very bad things

what kind of bad things 😳

**Comment by ItsBreadTime** [comment]
> > > smh jay
> > 
> > 
> > shush before i do bad things
> > # very bad things
> 
> what kind of bad things 😳

iphone 14, pro max 1tb - deep purple

**Pull request merged**
